<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="UTF-8" />
    <meta name="keywords" content="carddeck, card deck, card deck game, game, interesting, cool,crazy game,fun game, fun portfolio, funny game,"/>
    <meta name="description" content="Create you card deck for free!"/>
    <title>Card Deck</title>
    <link href="/assets/images/GlassesCreature.ico" type="image/x-icon" rel="shortcut icon">
    <link href="/assets/css/default.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/jquery.ui.css" rel="stylesheet" type="text/css" />
    <script src="/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.ui.js" type="text/javascript"></script>
</head>
<body>
<div id="container">
    <div id="header">
        &nbsp;
        <div id="user_panel">
            <?php echo $this->render('ajax/user-panel'); ?>
        </div>
    </div>
    <hr>
    <div id="content">
        <?php echo $this->render('default/dummy'); ?>
    </div>
</div>
<div id="card_selection" style="display:none;">
    <?php echo $this->render('ajax/card-selection'); ?>
</div>
<script src="/assets/js/carddeck.js" type="text/javascript"></script>
</body>
</html>
