<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="UTF-8" />
    <meta name="keywords" content="carddeck, card deck, card deck game, game, interesting, cool,crazy game,fun game, fun portfolio, funny game,"/>
    <meta name="description" content="Create you card deck for free!"/>
    <title>Create <?php echo ucfirst( $this->dbvalues ); ?></title>
    <link href="/assets/images/GlassesCreature.ico" type="image/x-icon" rel="shortcut icon">
    <link href="/assets/css/default.css" rel="stylesheet" type="text/css" >
</head>
<body>
    <div id="container">
        <div id="header">&nbsp;</div>
        <div id="content">
            <?php if( $this->dbvalues != "Nothing" ) : ?>
                <h1>Done...!</h1>
                <div id="notes">
                    Successfully created
                    <?php echo ( $this->dbvalues == "card" ) ? $this->cardcount . " new " . $this->dbvalues ."(s) " : " a new " . $this->dbvalues . " : <br>" . $this->skill ; ?>
                </div>
            <?php else : ?>
                <h1 class="invalid">Invalid Parameter</h1>
                <div id="notes">Unable to create card or skill.</div>
            <?php endif; ?>
        </div>
    </div>
    <script>
        function redirectToHomePage() {  location.href = "http://"+location.hostname; }
        setTimeout( "redirectToHomePage()" , 5000 );
    </script>
</body>
</html>